export class Ingredient {
    food_group : string; 
    food_code : string;
    type : string;
    food_name : string;
    guju_name : string;
    quantity : string;
    one_exchange : number; 
    energy_kj : number;
    energy_kcal: number;
    gi_value : number;
    gl_value : number;
    carbohydrate : number;
    protein : number;
    total_fibre : number;
    solublf : number;
    in_solublf : number;
    invisible_totalfat : number;
    visiblefat : number;
    thiamine : number;
    riboflavin : number;
    niacin : number;
    biotin : number;
    folates : number;
    ascorbic_Acid : number;
    vitamin_d2d3 : number;
    calcium : number;
    phosphorous : number;
    iron : number;
    sodium : number;
    potassium : number;
    zinc : number;
    magnesium : number;
    sfa : number;
    isActive : Boolean;
}